#switch on required packages
library(foreign)
library(ggplot2)
library(plyr)
library(Hmisc)
library(reshape2)
library(stringr)
library(lubridate)
library(MASS)
library(car)
library(ellipse)
library(RColorBrewer)
library(Formula)
library(party)
library(partykit)
library(rpart)
library(ROCR)
library(caret)
library(nutshell)
library(randomForest)
library(dataframe)
library(data.table)
#set options for digits and missing values handling
options(digits=3,na.action=na.exclude)
options(stringsAsFactors = FALSE)

       